#!/usr/bin/env python

import argparse
import itertools

parser = argparse.ArgumentParser(description="")
parser.add_argument('tickets', type=str, help="list of flight tickets")

args = parser.parse_args()

def process(tickets):
    try:
        all_tickets = []
        tickets = open(tickets).read().strip().split('\n')
        highest = 0
        for ticket in tickets:
            localticket = ticket
            local = 0
            local_row = 0
            local_col = 0
            moves = list(ticket.strip()) 
            for i in range(6,-1,-1):
                current_position = ticket[0]
                if current_position == 'B':
                    local_row += 2**i
                ticket = ticket[1:]
            for i in range(2, -1, -1):
                current_position = ticket[0]
                if current_position == 'R':
                    local_col += 2**i
                ticket = ticket[1:]
            local = local_row * 8 + local_col
            all_tickets.append(local)
            if local > highest:
                highest = local
        all_tickets = sorted(all_tickets)
        for i in range(1,len(all_tickets)+1):
            if i not in all_tickets:
                print(i)
        return highest

    except:
        print("Error reading batch file")
        raise

if __name__ == '__main__':
    tickets = args.tickets
    print(process(tickets))
