#!/usr/bin/env python

import argparse
import itertools

parser = argparse.ArgumentParser(description="")
parser.add_argument('forms', type=str, help="list of declaration forms")

args = parser.parse_args()

def process(ticket_list):
    try:
        total = 0
        groups = open(ticket_list).read().strip().split('\n\n')
        for group in groups:
            total_answers = {}
            answers = group.strip().split('\n')
            for answer in answers:
                for letter in answer:
                    if total_answers.get(letter, None):
                        total_answers[letter] += 1
                    else:
                        total_answers[letter] = 1
            allyes = list(filter(lambda x: total_answers[x] == len(answers), total_answers))
            total += len(allyes)
        return total

    except:
        print("Error reading list of forms")
        raise

if __name__ == '__main__':
    forms = args.forms
    print(process(forms))
