#!/usr/bin/env python

import argparse
import itertools

parser = argparse.ArgumentParser(description="")
parser.add_argument('batch', type=str, help="batch of passports")

args = parser.parse_args()

required_fields = ['byr', 'iyr', 'eyr', 'hgt', 'hcl', 'ecl', 'pid']
optional_fields = ['cid']

def process(batch):
    try:
        passports = open(batch).read().split('\n\n')
        valid = len(passports)
        for passport in passports:
            passport = passport.replace('\n', ' ').strip()
            for field in required_fields:
                if field not in passport:
                    valid -= 1
                    break
        return valid

    except:
        print("Error reading batch file")
        raise

if __name__ == '__main__':
    batch = args.batch
    print(process(batch))
